# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('saddr', models.CharField(max_length=100)),
                ('sschool', models.CharField(max_length=50)),
            ],
        ),
    ]
